url: "https://coderic.net"
title: "Coderic Hub"
description: "Centro de Conocimiento Corporativo - Tu portal centralizado para recursos, documentaci?n y contenidos de Coderic"
network: "HUB"
remote_theme: Coderic/coderic.org
